name: Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: |
          echo ${{ secrets.APPLICATION }} | base64 --decode > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml
          chmod +x ./gradlew
          ./gradlew test

      - name: Send Discord Alert on Failure
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Backend_Test_Fail_Alarm"
          DISCORD_EMBEDS: '[{
            "title": "⚠️ 테스트 실패! ⚠️",
            "description": "테스트가 실패하여 배포 브랜치 병합이 중단되었습니다. 🔴",
            "color": 16711680,
            "fields": [
              { "name": "Repository", "value": "${{ github.repository }}", "inline": true },
              { "name": "Commit", "value": "${{ github.sha }}", "inline": true },
              { "name": "Author", "value": "${{ github.actor }}", "inline": true },
              { "name": "🔗 Commit Link", "value": "[클릭하기](https://github.com/${{ github.repository }}/commit/${{ github.sha }})", "inline": false }
            ]
          }]'
